<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>a197c6da-f2ee-4912-b1e9-d46c7ab3631d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Zip Code</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents wf-futurapt-n5-active wf-futurapt-i5-active wf-futurapt-i3-active wf-futurapt-n4-active wf-futurapt-i4-active wf-futurapt-n3-active wf-futurapt-n6-active wf-futurapt-i6-active wf-freighttextpro-n4-active wf-freighttextpro-i4-active wf-freighttextpro-n7-active wf-freighttextpro-i7-active wf-freighttextpro-n6-active wf-freighttextpro-i6-active wf-futuraptcondensed-n4-active wf-futuraptcondensed-i4-active wf-futuraptcondensed-n5-active wf-futuraptcondensed-i5-active wf-futuraptcondensed-n7-active wf-futuraptcondensed-i7-active wf-futuraptcondensed-n8-active wf-futuraptcondensed-i8-active wf-freightdisplaypro-n4-active wf-freightdisplaypro-i4-active wf-active&quot;]/body[1]/main[1]/section[@class=&quot;c-generic-landing&quot;]/div[@class=&quot;c-regular-omd c-generic-landing__section js-regular-omd&quot;]/div[@class=&quot;c-regular-omd__wrapper o-wrapper&quot;]/div[@class=&quot;c-regular-omd__widget&quot;]/div[@class=&quot;c-omd-widget&quot;]/form[@class=&quot;c-omd-widget__zip-form&quot;]/div[@class=&quot;c-omd-widget__zip-fields&quot;]/label[@class=&quot;c-omd-widget__zip-input o-input o-input--text&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//input[@type='text']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your program'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clean eating designed for results'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Meals'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
